In [116]:
import os
import random
import shutil
import re
import pandas as pd
import numpy as np

In [59]:
#count scores
# data=pd.read_csv('BLE_clean.csv')
# data.rename(columns={'Student.Tracking.Id': 'student'}, inplace=True)
# data.drop_duplicates(subset=['student'],inplace=True)
# data

In [60]:
data=pd.read_csv('rer_all_audio_files_list_upd.csv')

In [61]:
data.drop_duplicates(inplace=True) #remove duplicates in place
data.dropna(subset=['student_id'], inplace=True) #remove NaN subjects

In [62]:
duplicates = data[data.duplicated(subset=['student_id', 'task_name', 'item_name', 'semester'], keep=False)]

duplicates=duplicates.sort_values(by=['student_id', 'task_name', 'item_name', 'semester'])

In [63]:
#duplicates.to_csv('rer_duplicate_items.csv', index=False)

In [64]:
# Get rows of df1 which are not in df2
no_duplicates = data.merge(duplicates, how='outer', indicator=True).query("_merge == 'left_only'").drop('_merge', axis=1)

In [65]:
#no_duplicates
#no_duplicates.to_csv('no_duplicates.csv', index=False)

In [66]:
# Split the strings in col1 based on ':'
no_duplicates[['task', 'new_col2']] = no_duplicates['task_name'].str.split(':', expand=True)

# Split the strings in new_col2 based on '('
no_duplicates[['task', 'new_col3']] = no_duplicates['task'].str.split('(', expand=True)

# Drop the unwanted columns
no_duplicates.drop(['new_col2', 'new_col3'], axis=1, inplace=True)

# Replace all '_' and ' ' characters in col1 with '' and also remove Practice and Items
no_duplicates['task'] = no_duplicates['task'].str.replace('-', '').str.replace(' ', '').str.replace('Items', '').str.replace('Practice', '')

In [67]:
no_duplicates['task'].unique()

array(['WPPSIPN', 'KTEALWR', 'NonwordRepetition', 'Synonyms',
       'WordReading', 'SetforVariability', 'KTEANWD',
       'GrowthMindsetQuestion', 'PearsonCopyrightKTEALWR',
       'PearsonCopyrightWPPSI', 'PearsonCopyrightKTEANWD',
       'PearsonCopyrightCELF', 'SentenceRepetition', 'NonwordReading',
       'Deletion', 'PictureNaming', 'Blending', 'DigitSpan',
       'VisualAttentionDirections', 'LetterNamingContext', 'RapidNaming',
       'LetterNamingIsolation', 'LetterSoundsContext', 'EVT3',
       'PearsonCopyrightEVT', 'RapidLetterNaming',
       'ChildVerbalAssentFormAssent', 'OralReadingFluency',
       'LetterSoundsIsolated', 'PairedAssoc.Learning',
       'RapidObjectNaming', 'PairedAssociatesLearning',
       'PairedAssociateLearning', 'ParentTechnologySurvey',
       'ChildVerbalAssentForm', 'Szynonyms', 'CELF_RS'], dtype=object)

In [ ]:
for index, row in no_duplicates.head(10).iterrows():
    semester = row['semester']
    grade = row['grade']
    audio_string = row['audio_string']
    assessment_name = row['assessment_name']
    task_name = row['task_name']
    item_name = row['item_name']
    student_id = row['student_id']

## non word repetition

In [114]:
# Filter rows of df where task is 'NonwordRepetition', 'SentenceRepetition', 'Deletion', or 'Blending'
#new_df = no_duplicates[no_duplicates['task'].isin(['NonwordRepetition', 'SentenceRepetition', 'Deletion', 'Blending'])]
NonwordRepetition_df = no_duplicates[no_duplicates['task'].isin(['NonwordRepetition'])]

In [117]:
# Split the strings in col1 based on '_'
NonwordRepetition_df['item'] = NonwordRepetition_df['item_name'].str.split('_', expand=True)[2]
NonwordRepetition_df['assessment_season'] = NonwordRepetition_df['assessment_name'].str.extract('(Fall|Winter|End)')
NonwordRepetition_df['assessment_season'] = NonwordRepetition_df['assessment_season'].str.lower()
NonwordRepetition_df['semester_season'] = NonwordRepetition_df['semester'].str.extract('(fall|winter|spring|end)')
NonwordRepetition_df['true_season'] = NonwordRepetition_df['semester_season'].fillna(NonwordRepetition_df['assessment_season']) #combine semester and assessment season columns
NonwordRepetition_df = NonwordRepetition_df[~NonwordRepetition_df['item'].isin(['S', 'A'])] #remove where item is 'S' or 'A' these don't line up with scores
where_nwr_bad=NonwordRepetition_df['item'].isin(['0013','0009', '0003', '0006', '0027', '0024', '0025', '0018', '0001','0017', '0015', '0016','9003', '9002' ])
NonwordRepetition_df['new_item']= NonwordRepetition_df[where_nwr_bad]['item_name'].str.split('_', expand=True)[3]
NonwordRepetition_df['item'] = NonwordRepetition_df['item'].replace(['0013','0009', '0003', '0006', '0027', '0024', '0025', '0018', '0001','0017', '0015', '0016','9003', '9002'], np.nan)
NonwordRepetition_df['true_item'] = NonwordRepetition_df['item'].fillna(NonwordRepetition_df['new_item']) #combine semester and assessment season columns
#load all_files for matching the folders
all_files=pd.read_csv('all_files.csv',header=None,names=['folder','audio_string'])
# merge the two dataframes on the 'key' column
NonwordRepetition_df = pd.merge(NonwordRepetition_df, all_files, on='audio_string', how='left')
# display the updated dataframe
#merged_df

In [128]:
NonwordRepetition_df['true_item'].unique()

array(['kuhcheyvap', 'moid', 'vergowfduhboik', 'vugoobuhcheen',
       'toovhohgneeb', 'gahyfmowb', 'kahybeymookdowb',
       'kefnuhvohkmerforb', 'meevteyfohg', 'goomdachahytowb', 'geemtohf',
       'feeb', 'boifneekahyb', 'powfberkahym', 'choig', 'buhkahypvermoid',
       'neemvoik', 'fuhmoibnagoopchey', 'guhchahdurnam', 'kahyvdowk',
       'dakgowmuhkoov', 'vohp', 'koodverheek', 'teevkahnahyd',
       'neyvoocheeb', 'mowteydpermeek', 'powmfoibeyvohk',
       'cheykfuhmowdoo', 'cheytuhmoofeek', 'heeg', 'merchagahyk', 'chav',
       'verdboim', 'kurcheypheef', 'duhpeygeem', 'murvoipgeeteyf', 'toif',
       'deefkurvuhgoob', 'gahyf', 'chuhdoifkooteyb', 'purvanuhkahyd',
       'dahpowcheykgerfeem', 'turkvowfoip', 'murdapfuhgowt',
       'vuhchohfoiteeg', 'nowb', 'kahyberchoitahvoom', 'kahyfeep',
       'voogfowboik', 'mookbowf', 'moif', 'noimahyd', 'vahftombuhgoid',
       'duhpakuhtayf', 'towb', 'nafburkud', 'vuhbowkeiv', 'cheebfooheyg',
       'poivtowb', 'chohfmoonorbkahyheyb', 'heefkuhpevnohg',
       'hevdohfteeg', 'neygmuhgefdeeb', 'hevkeegorbpuhtohf',
       'towneebvookahyb', 'tevkeeberfowt', 'mowp', 'duhhoigmoofeyb',
       'keevnamoiftowg', 'cheyvpoigefheeb', 'kahymheypoivtuhvook',
       'boovteypahygfuhdap', 'koovnorb', 'forbmuhteevheynohg',
       'bohfneymeevgorb', 'nohftowb', 'vowkpoikefteev', 'hevgeembohf',
       'mohgheedoovnoim', 'chohmgowhoidfeeg', 'toifkerpohgvoomef',
       'chohvderfowbneeteyf', 'davhowterboif', 'neygfowtvahkeeb',
       'voimkooheefgahyp', 'poivnuhhowbmookahyd', 'tevbeenorb',
       'merpahyvtohfbeyg', 'dorbfuhcheemgeenad', 'nohfteyg',
       'kefdowgeemfoik', 'cheyvpuhgef', 'neekperteyvkoohowb',
       'cheygdoiteeg', 'noikteyvapheeb', 'neygfohpevdak', 'heyfkowb',
       'voogpeymowbtuhfoib', 'vohgefheyg', 'torbhowdoovmohk', 'cheemkeev',
       'tohfpeeg', 'kahyb', 'forbtermahyvnad', 'choibeygorb',
       'peemteyvoogkuhmef', 'vahtoifkerheev', 'derfoimhowk',
       'nowbmoipahyvkeeg', 'dowkheefpuhgoov', 'kahymgowboov',
       'nowbheektervohk', 'bowfgeechoib', 'geemferbowvkervoog',
       'muhheegperteyvneek', 'nuhvoikheyf', 'vooktowf', 'chohgfeem',
       'koofpergoibneek', 'koofdowb', 'huhvohkdooteyf', 'gowb',
       'moifteyvook', 'tuhneydvoocheeb', 'voimkeeg', 'pahyb',
       'poiteyvohkmuhowb', 'gowfdoikeem', 'moidheyf', 'duhgeepvohk', 'a',
       'neymooheyfgowb', 'bowgeefmuhtoib', 'kahymneevohkmuhfoig',
       'goifpahyd', 'deevmeygpohf', 'bowmhoideegmohf', 'geftohgneeb',
       'doovkeepohfmerbeyg', 'chahmkuhdorbfeyb', 'vookmeevfahbeyp'],
      dtype=object)

In [119]:
NonwordRepetition_df.to_csv('testing.csv', index=False)

### add the folders column

/tmp/ipykernel_31867/8668759.py:2: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  all_files=pd.read_csv('all_files.csv',header=None,names=['folder','audio_string'])

In [147]:
NonwordRepetition_df

,semester,grade,audio_string,date,assessment_name,task_name,item_name,student_id,task,item,assessment_season,semester_season,true_season,new_item,true_item,folder
0,Y4_winter,KG,VirtualWinter2022Day1KF1-NonwordRepetitionTask...,05/09/2022 11:25:34,Virtual Winter 2022 Day 1 (K: F1),Nonword Repetition: Task A (K Winter 22),NWR_10_kuhcheyvap_012,55_21_0_3093,NonwordRepetition,kuhcheyvap,winter,winter,winter,NaN,kuhcheyvap,20220509
1,Y4_winter,KG,VirtualWinter2022Day1KF1-NonwordRepetitionTask...,05/09/2022 11:37:45,Virtual Winter 2022 Day 1 (K: F1),Nonword Repetition: Task A (K Winter 22),NWR_94_moid_0,55_21_0_3098,NonwordRepetition,moid,winter,winter,winter,NaN,moid,20220509
2,Y4_winter,KG,VirtualWinter2022Day1KF1-NonwordRepetitionTask...,05/09/2022 10:54:49,Virtual Winter 2022 Day 1 (K: F1),Nonword Repetition: Task A (K Winter 22),NWR_96_vergowfduhboik_0,55_21_0_3066,NonwordRepetition,vergowfduhboik,winter,winter,winter,NaN,vergowfduhboik,20220509
3,Y4_winter,KG,VirtualWinter2022Day1KF1-NonwordRepetitionTask...,05/09/2022 11:25:39,Virtual Winter 2022 Day 1 (K: F1),Nonword Repetition: Task A (K Winter 22),NWR_11_vugoobuhcheen_012,55_21_0_3093,NonwordRepetition,vugoobuhcheen,winter,winter,winter,NaN,vugoobuhcheen,20220509
4,Y4_winter,KG,VirtualWinter2022Day1KF1-NonwordRepetitionTask...,05/09/2022 10:20:52,Virtual Winter 2022 Day 1 (K: F1),Nonword Repetition: Task A (K Winter 22),NWR_99_toovhohgneeb_0,55_21_0_3068,NonwordRepetition,toovhohgneeb,winter,winter,winter,NaN,toovhohgneeb,20220509
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30980,Y3,1,VirtualFall2020Day1G1F1-NonwordRepetitionTaskA...,2021-02-19 00:00:00,Virtual Fall 2020 Day 1 (G1: F1),Nonword Repetition: Task A (1st Fall 20),NWR_11_vugoobuhcheen_012,11_20_0_2479,NonwordRepetition,vugoobuhcheen,fall,NaN,fall,NaN,vugoobuhcheen,20210219
30981,Y3,1,VirtualFall2020Day1G1F1-NonwordRepetitionTaskA...,2021-02-19 00:00:00,Virtual Fall 2020 Day 1 (G1: F1),Nonword Repetition: Task A (1st Fall 20),NWR_0135_torbhowdoovmohk,11_20_0_2479,NonwordRepetition,torbhowdoovmohk,fall,NaN,fall,NaN,torbhowdoovmohk,20210219
30982,Y3,1,VirtualFall2020Day1G1F1-NonwordRepetitionTaskA...,2021-02-19 00:00:00,Virtual Fall 2020 Day 1 (G1: F1),Nonword Repetition: Task A (1st Fall 20),NWR_0138_neekperteyvkoohowb,11_20_0_2479,NonwordRepetition,neekperteyvkoohowb,fall,NaN,fall,NaN,neekperteyvkoohowb,20210219
30983,Y3,1,VirtualFall2020Day1G1F1-NonwordRepetitionTaskA...,2021-02-19 00:00:00,Virtual Fall 2020 Day 1 (G1: F1),Nonword Repetition: Task A (1st Fall 20),NWR_0134_neygfohpevdak,11_20_0_2479,NonwordRepetition,neygfohpevdak,fall,NaN,fall,NaN,neygfohpevdak,20210219
30984,Y3,1,VirtualFall2020Day1G1F1-NonwordRepetitionTaskA...,2021-02-19 00:00:00,Virtual Fall 2020 Day 1 (G1: F1),Nonword Repetition: Task A (1st Fall 20),NWR_0132_vohgefheyg,11_20_0_2479,NonwordRepetition,vohgefheyg,fall,NaN,fall,NaN,vohgefheyg,20210219

## Scores

In [81]:
#NonwordRepetition_df[NonwordRepetition_df['item'].isin(['S','A','9003','9002'])] #some bad ones to ask about

In [83]:
#NonwordRepetition_df['item'].unique()

In [34]:
scores_df=pd.read_csv('NWR_clean.csv')
scores_df.rename(columns={'Student.Tracking.Id': 'student'}, inplace=True)

In [35]:
scores_df

,uniqueid,student,Grade,burgahm,dak,foobuhneech,goomdachahytowb,kahyvoip,kuhcheyvap,moif,...,forbtermahyvnad,kahyb,peemteyvoogkuhmef,tohfpeeg,vahtoifkerheev,cheyvpuhgef,dorbfuhcheemgeenad,kefdowgeemfoik,merpahyvtohfbeyg,poivnuhhowbmookahyd
0,nwrfall18_1,11_18_0_0001,KG,1.0,1.0,1.0,0.0,1.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,nwrfall18_2,11_18_0_0004,KG,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,nwrfall18_3,11_18_0_0005,KG,1.0,1.0,1.0,1.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,nwrfall18_4,11_18_0_0006,KG,1.0,1.0,1.0,0.0,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,nwrfall18_5,11_18_0_0007,KG,1.0,1.0,1.0,0.0,1.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3479,nwrspring23_565,11_22_0_4289,2,NaN,NaN,NaN,1.0,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,1.0,0.0
3480,nwrspring23_566,11_22_0_4291,2,NaN,NaN,NaN,0.0,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,1.0
3481,nwrspring23_567,11_22_0_4293,2,NaN,NaN,NaN,1.0,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0
3482,nwrspring23_568,11_22_0_4295,2,NaN,NaN,NaN,1.0,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,0.0,1.0,0.0,0.0
3483,nwrspring23_569,11_22_0_4297,2,NaN,NaN,NaN,0.0,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0

In [36]:
scores_df[scores_df.duplicated(subset=['student'], keep=False)].sort_values(by=['student'])

#duplicates=duplicates.sort_values(by=['student_id', 'task_name', 'item_name', 'semester'])

,uniqueid,student,Grade,burgahm,dak,foobuhneech,goomdachahytowb,kahyvoip,kuhcheyvap,moif,...,forbtermahyvnad,kahyb,peemteyvoogkuhmef,tohfpeeg,vahtoifkerheev,cheyvpuhgef,dorbfuhcheemgeenad,kefdowgeemfoik,merpahyvtohfbeyg,poivnuhhowbmookahyd
0,nwrfall18_1,11_18_0_0001,KG,1.0,1.0,1.0,0.0,1.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2772,nwrspring21_110,11_18_0_0001,2,NaN,NaN,NaN,1.0,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
215,nwrfall19_1,11_18_0_0001,1,NaN,NaN,NaN,0.0,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1443,nwrspring20_1,11_18_0_0001,1,NaN,NaN,NaN,0.0,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1237,nwrspring19_1,11_18_0_0001,KG,NaN,NaN,NaN,0.0,NaN,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3255,nwrspring23_341,66_22_0_4092,2,NaN,NaN,NaN,0.0,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3256,nwrspring23_342,66_22_0_4117,2,NaN,NaN,NaN,1.0,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3472,nwrspring23_558,66_22_0_4117,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0
3257,nwrspring23_343,66_22_0_4119,2,NaN,NaN,NaN,0.0,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3473,nwrspring23_559,66_22_0_4119,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0

In [37]:
# Extract the season from uniqueid
scores_df['season'] = scores_df['uniqueid'].str.extract('(fall|spring|winter)')

In [38]:
# Replace 'winter' with 'spring' in col1
scores_df['season_winter'] = scores_df['season'].replace('spring', 'winter')

In [39]:
scores_df

,uniqueid,student,Grade,burgahm,dak,foobuhneech,goomdachahytowb,kahyvoip,kuhcheyvap,moif,...,peemteyvoogkuhmef,tohfpeeg,vahtoifkerheev,cheyvpuhgef,dorbfuhcheemgeenad,kefdowgeemfoik,merpahyvtohfbeyg,poivnuhhowbmookahyd,season,season_winter
0,nwrfall18_1,11_18_0_0001,KG,1.0,1.0,1.0,0.0,1.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,fall,fall
1,nwrfall18_2,11_18_0_0004,KG,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,fall,fall
2,nwrfall18_3,11_18_0_0005,KG,1.0,1.0,1.0,1.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,fall,fall
3,nwrfall18_4,11_18_0_0006,KG,1.0,1.0,1.0,0.0,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,fall,fall
4,nwrfall18_5,11_18_0_0007,KG,1.0,1.0,1.0,0.0,1.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,fall,fall
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3479,nwrspring23_565,11_22_0_4289,2,NaN,NaN,NaN,1.0,NaN,0.0,NaN,...,NaN,NaN,NaN,1.0,0.0,0.0,1.0,0.0,spring,winter
3480,nwrspring23_566,11_22_0_4291,2,NaN,NaN,NaN,0.0,NaN,1.0,NaN,...,NaN,NaN,NaN,1.0,0.0,0.0,0.0,1.0,spring,winter
3481,nwrspring23_567,11_22_0_4293,2,NaN,NaN,NaN,1.0,NaN,0.0,NaN,...,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,spring,winter
3482,nwrspring23_568,11_22_0_4295,2,NaN,NaN,NaN,1.0,NaN,1.0,NaN,...,NaN,NaN,NaN,1.0,0.0,1.0,0.0,0.0,spring,winter
3483,nwrspring23_569,11_22_0_4297,2,NaN,NaN,NaN,0.0,NaN,0.0,NaN,...,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,spring,winter

## see which scores are potentially duplicated (they are not, they have different items)

In [40]:
scores_df_dupe = scores_df.loc[:, ['uniqueid', 'student', 'Grade', 'season', 'season_winter']]
scores_df_dupe

duplicated_scores=scores_df[scores_df.duplicated(subset=['student','Grade','season_winter'],keep=False)].sort_values(by=['student','Grade','season'])
duplicated_scores.to_csv('rer_duplicate_scores_NWR.csv', index=False)

### loop through the items

### get the unique assessments as a test to match and loop through

In [18]:
assessments_df=NonwordRepetition_df.drop_duplicates(subset=['student_id','semester','grade']) #remove duplicates in place
#for index, row in assessments_df.iterrows():
for index, row in assessments_df.head(70).iterrows():
    semester = row['semester']
    grade = row['grade']
    audio_string = row['audio_string']
    assessment_name = row['assessment_name']
    task_name = row['task_name']
    item_name = row['item_name']
    student_id = row['student_id']
    task = row['task']
    item = row['item']
    assessment_season = row['assessment_season']
    semester_season = row['semester_season']
    
    count = scores_df[(scores_df['student'] == student_id) & (scores_df['Grade'] == grade) & (scores_df['season_winter'] == semester_season)].shape[0]
    if count > 1:
        print(count)
        print(audio_string)
        ided= scores_df[(scores_df['student'] == student_id) & (scores_df['Grade'] == grade) & (scores_df['season_winter'] == semester_season)]

NameError: name 'scores_df' is not defined